name: Linux build

env:
  CPU_TARGET: cpu
  FT2_VERSION: ft2
  PROJECT_VERSION: "0.96a"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cpu_target: [ "000", "020", "v4e" ]
        ft2_version: [ "2.2.1", "2.5.2", "2.8.1", "2.10.2" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: ./.scripts/build.sh
